### ISSUE TITLE
Image background

### ISSUE THREAD

**Issue by satyabonakala-hub** [lmonari5/molecule-icon-generator#3]
Hi Luca, 
Many thanks for the wonderful tool. 
Is it possible to create images with different backgrounds instead of white colour?

kind regards,
Satya

**Comment by Lucandia** [comment]
Hi Satya,
 Thanks a lot for your feedback!
 I've added a 'Background' item in the 'Change the colour:' dropdown menu! You can change it to adjust the background.
(if the background is set to white, it will be transparent in the SVG file)
Let me know if it works fine for you!
Best,
 Luca

**Comment by satyabonakala-hub** [comment]
Excellent!, Appreciate your efforts. It's working for me. 

thanks,
Satya
